inherit_from: ./config/default_edge.yml

Naming/FileName:
  Enabled: true
  Exclude:
    - "wurl-rubocop-style.gemspec"

AllCops:
  Exclude:
    # These use github's rules and are out of scope for us.
    - 'lib/rubocop/cop/github/**/*.*'
    - vendor/**/*
